### ISSUE TITLE
Add more options in config.ts to make it easier to switch to different modes

### ISSUE THREAD

**Issue by hidacow** [Xerxes-2/mjai-batch-review#2]
Currently some configs are hardcoded, and one have to modify multiple places to switch to another mode (like 3-player mahjong or only want to review the games in Jade Room), which is inconvenient and not elegant.

For example, one have to do the following:

1. Change multiple occurances of `CONFIGURATIONS.DEFAULT` to the configuration of 3p (`CONFIGURATIONS.ikeda`) in `src/amae-koromo/utils/conf.ts`. (can also replace the `DEFAULT` with `ikeda`)
2. Change hardcoded reviewCompatibleModes (`[16, 12, 9]`) to eg. `[26,25,24,23,22,21]` for 3p in `src/utils.ts` 
3. Change `mjaiReviewer`, `mortal`, `mortalCfg` in `src/config.ts` to the 3p-compatible reviewer and mortal binary path

Maybe more options can be added to `config.ts` as well as refactoring some code in other places to make it easier to change these internal configurations

**Comment by Xerxes-2** [comment]
This script is not intended for use in 3p. However, I will be happy to see a pull request for this feature.
